version: '3.8'
services:
  web:
    build: .
    container_name: forgeojson
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
networks:
  metanet1:
    driver: bridge
